### ISSUE TITLE
confedit.exe contains malicious behavior

### ISSUE THREAD

**Issue by antnks** [digiampietro/adbtools2#5]
Full report:
https://www.virustotal.com/gui/file/674e87ac368c98beb25d7665d364e13d0700cd14d2c1180f786257627a0a9093/detection

Detection ratio: 8/64
Processes created:
C:\674e87ac368c98beb25d7665d364e13d0700cd14d2c1180f786257627a0a9093 C:\674e87ac368c98beb25d7665d364e13d0700cd14d2c1180f786257627a0a9093""

**Comment by bovirus** [comment]
UI'm so sorry but is not a virus.
It's a false positive.

All exe file created with programs like AutoHotkey aree reported (wrong) by some antivirus as maliciopus sofwtare.

My McAfee scan it and didn't report any problem.

**Comment by digiampietro** [comment]
It is a false positive.
The python source has been "compiled" and it seems that this creates executables interpreted as malicious by some antivirus.
It is always possible to use the Python source, the .exe is only for convenience to be able to run the software without a Python installation.
