### ISSUE TITLE
Wishlist: enabling configuration change to actually enable hairpinning.

### ISSUE THREAD

**Issue by callegar** [digiampietro/adbtools2#7]
One of the issues with the DWA 5592 router is that it advertises some hairpinning functionality (both in the manual and in the web interface), but this does not work as expected.

The idea with hairpinning is that if you have your wan interface at some public address PP.PP.PP.PP and an internal LAN at LL.LL.LL.xx and you have an internal host at LL.LL.LL.XX, once you have configured some port forwarding so that external traffic getting to PP.PP.PP.PP on port PA goes to LL.LL.LL.XX on port LA, then connecting from the outside to  PP.PP.PP.PP:PA should get you to talk to  LL.LL.LL.XX:LA, but also connecting *from the inside* (e.g. from some LL.LL.LL.YY) to PP.PP.PP.PP:PA should get you to LL.LL.LL.XX:LA.

This is important to be able to access internal services in the same way regardless whether you are doing this from the inside or the outside of your LAN.

Unfortunately, for the DWA 5592 this only works among internal hosts that are attached to the ethernet ports of the device. With reference to the previous example, if both LL.LL.LL.XX and LL.LL.LL.YY are attached using a cable, then LL.LL.LL.YY contacting PP:PP:PP:PP:PA gets to LL.LL.LL.XX:LA. However, if LL.LL.LL.YY is attached via WIFI, this does not work. Incidentally, if both LL.LL.LL.XX and LL.LL.LL.YY are attached to the WIFI, the connection *sometimes* works.

This situation hinders the very purpose of hairpinning badly and appears to be caused by the bridge configuration and/or the netfilter/nftables configuration, both of which should be fixable having root access to the router.

**Describe the solution you'd like**

Would be great to know how to alter the configuration of the bridge/netfilter/nftables in order to make the hairpinning actually work. A modified firmware directly allowing this change would be great.

**Comment by bovirus** [comment]
@callegar 

Your request is out of scope for this project.

This project change the configuration file (not the firmware) of the modem.

Then your request for a modified version of the firmware is OT here.

**Comment by callegar** [comment]
@bovirus 

Most likely you are right! If so, I am sorry for the noise. Maybe, I got too hopeful for the fact that the project is actually providing a modified firmware to help with the primary goal for changing the configuration and I thought that it would have been great if this firmware could also allow some form of shell *access* to act on the modem bridge/netfilter configuration too.

As a matter of fact I think that I had already spoken about this issue of the modem to @digiampietro when this project was in an earlier development stage and I was hopeful that with the root access there could be some workaround.

If you do not mind, I'd like if this bug could stay here (even in closed form, maybe) to formally document a significant deficiency of the apparatus, so that people who are bitten by it can google a quick confirmation that the issue is with the modem and not with what they try to achieve.

**Comment by bovirus** [comment]
@callegar

I'm not agree to leave here the info about firmware bug.
For me this project didn't support firmware and there is no reason to leave here open a ticket about a firmware issue that is not related to this github project.

Please post your problem not here but in D-Link support forum.
The D-Link support forums are the only official support forum for the modem.

**Comment by callegar** [comment]
It was not meant to complain about the bug, rather than to encourage finding ways to alter the configuration of the netfilter/nftables (that is to alter the modem configuration beyond what can be done with the modem web interface). In any case feel free to remove everything.
